### ISSUE TITLE
Image Format

### ISSUE THREAD

**Issue by LynxStar** [lawrancej/CompilerDesign#32]
We should reconsider using vectors for our image renders and move to a more universally supported raster such a .jpg or .png.  The .svg files are sufficient for designing the graphics but should be rendered to a separate format for use throughout the documentation. You would be hard pressed to find a browser that does not support .png rasters out of the box in this day and age.  Otherwise we restrict users to a very select few markdown parsers and must assume they have the correct extensions for the engine installed. (I think this counter-intuitive to our cross platform mindset. (I am assuming we want this to be cross-platform))

Something else to bare in mind.  If we are going to split the images into a development and production version our hierarchy should replace that.  Maybe Images/Raw or Images/Source for the svg, psd, or any other internal development format and then Images/Raster for rendered .png.

I can implement this change and render the .svg to png and update the markdown links if you would like.

**Comment by lawrancej** [comment]
I'm a bit confused. 

Regarding the first paragraph, when I look at the output of `generate.sh html`, Firefox, Chrome, and _gasp_ even Internet Explorer renders the SVG just fine. Also, why should the markdown parser care about the image format?  I suppose we could translate the SVG to PNG if people use browsers that still don't support SVG by now. For a public facing web site, that seems sensible, as not everyone has a good browser.

Regarding the second paragraph, the generate.sh script already copies the images folder as a subfolder in `build/` When generating the PDF version of the book, the Batik rasterizer transcodes SVG into PDF.

Regarding the third paragraph, incidentally, the Batik rasterizer also also supports rasterizing SVG to PNG. So, if you'd like to add support for that in the `generate.sh html` target, go ahead. I'd probably make it optional for rasterizing, since it'd only slow down the build, and really seems to benefit only people using old browsers.

I'm thinking this issue shouldn't apply for the epub target, since svg support is a requirement for epub readers.

**Comment by LynxStar** [comment]
Fair enough.
